kind: Job
apiVersion: batch/v1
metadata:
  name: nginx-job
  namespace: nginx-ns
spec:
  completions: 2
  parallelism: 3
  template:
    metadata:
      name: nginx-job
      labels:
        app: nginx-batch-task
    spec:
      containers:
        - name: batch-con
          image: busybox:latest
          command: ["sh", "-c", "echo 'Hello from Job' && sleep 10"]

      restartPolicy: Never
